GET http://localhost:3003/users
###

POST http://localhost:3003/users/signup
Content-Type: application/json

{
  "name": "Beltrano",
  "email": "beltrano@email.com",
  "password": "beltrano123",
  "role": "NORMAL"
}
###

POST http://localhost:3003/users/signup
Content-Type: application/json

{
  "name": "Lincon",
  "email": "lincon@email.com",
  "password": "lincon00",
  "role": "NORMAL"
}
###
